{
  if (Future.class.isAssignableFrom(method.getReturnType())) {
    ReflectionUtils.rethrowException(ex);
  }
 else {
    try {
      this.exceptionHandler.handleUncaughtException(ex,method,params);
    }
 catch (    Throwable ex2) {
      logger.error("Exception handler for async method '" + method.toGenericString() + "' threw unexpected exception itself",ex2);
    }
  }
}
