{
  originalThreadName=Thread.currentThread().getName();
  GenericApplicationContext context=new GenericApplicationContext();
  context.registerBeanDefinition("asyncTest",new RootBeanDefinition(AsyncMethodBean.class));
  context.registerBeanDefinition("autoProxyCreator",new RootBeanDefinition(DefaultAdvisorAutoProxyCreator.class));
  context.registerBeanDefinition("asyncAdvisor",new RootBeanDefinition(AsyncAnnotationAdvisor.class));
  context.refresh();
  AsyncMethodBean asyncTest=context.getBean("asyncTest",AsyncMethodBean.class);
  asyncTest.doNothing(5);
  asyncTest.doSomething(10);
  Future<String> future=asyncTest.returnSomething(20);
  assertEquals("20",future.get());
  ListenableFuture<String> listenableFuture=asyncTest.returnSomethingListenable(20);
  assertEquals("20",listenableFuture.get());
  CompletableFuture<String> completableFuture=asyncTest.returnSomethingCompletable(20);
  assertEquals("20",completableFuture.get());
  try {
    asyncTest.returnSomething(0).get();
    fail("Should have thrown ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertTrue(ex.getCause() instanceof IllegalArgumentException);
  }
  try {
    asyncTest.returnSomething(-1).get();
    fail("Should have thrown ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertTrue(ex.getCause() instanceof IOException);
  }
  try {
    asyncTest.returnSomethingListenable(0).get();
    fail("Should have thrown ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertTrue(ex.getCause() instanceof IllegalArgumentException);
  }
  try {
    asyncTest.returnSomethingListenable(-1).get();
    fail("Should have thrown ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertTrue(ex.getCause() instanceof IOException);
  }
  try {
    asyncTest.returnSomethingCompletable(0).get();
    fail("Should have thrown ExecutionException");
  }
 catch (  ExecutionException ex) {
    assertTrue(ex.getCause() instanceof IllegalArgumentException);
  }
}
