{
  try {
    if (this.executionException != null) {
      Throwable cause=this.executionException.getCause();
      failureCallback.onFailure(cause != null ? cause : this.executionException);
    }
 else {
      successCallback.onSuccess(this.value);
    }
  }
 catch (  Throwable ex) {
  }
}
