{
  try {
    this.result=getNext().call();
  }
 catch (  Exception ex) {
    this.exception=ex;
    throw ex;
  }
  return this.result;
}
