{
  Throwable testException=null;
  List<Throwable> errors=new ArrayList<Throwable>();
  try {
    this.next.evaluate();
  }
 catch (  Throwable e) {
    testException=e;
    errors.add(e);
  }
  try {
    this.testContextManager.afterTestMethod(this.testInstance,this.testMethod,testException);
  }
 catch (  Exception e) {
    errors.add(e);
  }
  if (errors.isEmpty()) {
    return;
  }
  if (errors.size() == 1) {
    throw errors.get(0);
  }
  throw new MultipleFailureException(errors);
}
