{
  ConfigurableApplicationContext context=initContext(new RootBeanDefinition(AsyncAnnotationBeanPostProcessor.class));
  ITestBean testBean=context.getBean("target",ITestBean.class);
  final Future<Object> result=testBean.failWithFuture();
  try {
    result.get();
  }
 catch (  InterruptedException ex) {
    fail("Should not have failed with InterruptedException: " + ex);
  }
catch (  ExecutionException ex) {
    assertEquals("Wrong exception cause",UnsupportedOperationException.class,ex.getCause().getClass());
  }
}
