{
  final Exception ex=new Exception();
  try {
    testRollback(new TransactionOperationCallback(){
      public Object performTransactionalOperation() throws Throwable {
        return new SubclassOfClassWithTransactionalMethodAnnotation().echo(ex);
      }
    }
,false);
    fail("Should have thrown Exception");
  }
 catch (  Exception ex2) {
    assertSame(ex,ex2);
  }
}
